name = "JuliaMono"
uuid = "3ddd733a-d0fc-4af2-aaf7-62a5c76fb4e7"
authors = ["Simeon Schaub <simeondavidschaub99@gmail.com>"]
version = "0.1.0"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
Pkg = "1.3"
julia = "1.3"

[extras]
Fontconfig_jll = "a3f928ae-7b40-5064-980b-68af3947d34b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Fontconfig_jll", "Test"]
